version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.nginx-proxy.nginx-proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=kevinbiro99@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-kevinbiro99
    container_name: frontend
    restart: always
    expose:
      - 5173
    environment:
      - VIRTUAL_HOST=quiz-master.tech
      - LETSENCRYPT_HOST=quiz-master.tech

  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-kevinbiro99
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - 3000
    environment:
      - DB_HOST=postgres
      - VIRTUAL_HOST=api.quiz-master.tech
      - LETSENCRYPT_HOST=api.quiz-master.tech
    depends_on:
      - postgres

  postgres:
    env_file:
      - ./backend/.env
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
