version: "3.7"

services:
  frontend:
    build: ./frontend/vue-project
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/vue-project/.env

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    env_file:
      - ./backend/.env
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
