version: "3.7"

services:
  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./nginx/custom-spa.conf:/etc/nginx/conf.d/custom-spa.conf:ro
    labels:
      - com.github.nginx-proxy.nginx-proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=kevinbiro99@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  frontend:
    image: ghcr.io/kevinbiro99/frontend-kevinbiro99
    build: ./frontend/vue-project
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/vue-project/.env
    expose:
      - 5173
    environment:
      - VIRTUAL_HOST=quiz-master.tech
      - LETSENCRYPT_HOST=quiz-master.tech
    volumes:
      - ./frontend/vue-project:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    image: ghcr.io/kevinbiro99/backend-kevinbiro99
    container_name: backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - 3000
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - VIRTUAL_HOST=api.quiz-master.tech
      - LETSENCRYPT_HOST=api.quiz-master.tech
    depends_on:
      - postgres

  postgres:
    env_file:
      - ./backend/.env
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
